name: Ubuntu
run-name: ${{ github.actor }} is building on ubuntu by GitHub Actions 🚀
on: [workflow_dispatch, push]

jobs:
  Build:
    env:
      BUILD_TYPE: Release
      SYSTEM_LIB_DIR: /usr/lib/x86_64-linux-gnu
      TRIPLET: x64-ubuntu 

    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: List workspace before build
        run: find . | grep -v '\.git' | grep -v vcpkg | grep -v include
        shell: bash

      - name: install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libprotobuf-dev protobuf-compiler liblz4-dev libcurl4-openssl-dev
          version: 1.0
          execute_install_scripts: true

      - name: cmake configure
        run: |
          cmake -B build -DBUILD_SHARE_LIBS=ON -DVERBOSE=ON -DBUILD_SAMPLE=ON \
              -DBUILD_TESTS=ON  \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: build
        run: |
          cmake --build build --clean-first --config ${{env.BUILD_TYPE}}
  
      - name: install
        run: |
          cmake --install build --prefix ${{github.workspace}}
      
      # - name: test build standalone sample
      #   run:
      #     | 
      #       cmake -B build -DCMAKE_BUILD_TYPE=Release
      #       cmake --build build --clean-first --config Release
      #       rm -rf build
      #   shell: bash
      #   working-directory: ${{github.workspace}}/aliyun-log-cpp-sdk/build  

      
      - name: copy libs from system and repo
        run: |
              mkdir -p ${{env.TRIPLET}}
                cp $SYSTEM_LIB_DIR/liblz4.* ./${{env.TRIPLET}}/
                cp $SYSTEM_LIB_DIR/libprotobuf.* ./${{env.TRIPLET}}/
                cp $SYSTEM_LIB_DIR/libcurl* ./${{env.TRIPLET}}/

        working-directory:  ${{github.workspace}}/lib

      - run: mkdir -p release 
        name: mkdir

      # - name: Set env
      #   run: echo "GITHUB_SHA_SHAORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      # - name: Set env
      #   run: echo "TARGET_FILE=release/ubuntu-x64-${GITHUB_SHA_SHAORT}.tar.gz" >> $GITHUB_ENV  

      - name: Set env
        run: echo "TARGET_FILE=release/${{env.TRIPLET}}-latest.tar.gz" >> "$GITHUB_ENV"
      
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            bin lib include cmake example test *.cpp *.h *.md Makefile *.proto
          outPath: ${{env.TARGET_FILE}}

      - name: cat tar file info
        run: |
          ls -l ${{env.TARGET_FILE}}

      - name: save as aritifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.TRIPLET}}-latest-artifact
          path: ${{env.TARGET_FILE}}
          retention-days: 7
